/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package chatbot_with_database;
import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author chondroseto
 */
public class Chat extends javax.swing.JFrame {
        Connection con;
        Statement stat;
        ResultSet rs;
        String sql;
        int status;
        int counter;

    /**
     * Creates new form Chat
     */
    public Chat() {
        initComponents();
        ConnectDatabase DB = new ConnectDatabase();
        DB.config();
        con = DB.con;
        stat = DB.stm;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TA = new javax.swing.JTextArea();
        TF = new javax.swing.JTextField();
        send_btn = new javax.swing.JButton();
        menubar = new javax.swing.JMenuBar();
        menu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TA.setEditable(false);
        TA.setColumns(20);
        TA.setRows(5);
        TA.setText("ketik 'help' untuk melihat daftar kata kunci\n\nAI     : Selamat Datang, Ada yang bisa saya bantu? ");
        jScrollPane1.setViewportView(TA);

        send_btn.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        send_btn.setText("Kirim");
        send_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                send_btnActionPerformed(evt);
            }
        });

        menu2.setText("Log Out");
        menu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu2ActionPerformed(evt);
            }
        });
        menubar.add(menu2);

        setJMenuBar(menubar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(TF)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(send_btn)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 474, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(send_btn))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void send_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_send_btnActionPerformed
        // TODO add your handling code here:
        status=0;
        String psn=TF.getText();    // memasukan input user ke variable pesan
        TA.append("\nYou : "+psn);  // menampilkan variable pesan ke textarea
        psn = psn.toLowerCase();    //mengkonvert huruf ke huruf kecil semua
        try {
            sql = "SELECT * FROM pengetahuan_umum";
            rs = stat.executeQuery(sql);
            while(rs.next()){
                String[] kata = rs.getString("kata_kunci").split(","); // memsplit kata kunci yang terdiri dari banyak keyword
                for (counter = 0; counter < kata.length; counter++){
                    if(psn.contains(kata[counter])){ // menyamakan input user dengan kata kunci yang tersedia di database
                        status = status+1;
                        if(status==1){
                            bot(rs.getString("jawaban")); // jika sesuai maka AI menjawab
                        }
                    }
                }
            }
            TF.setText("");
            if(status==0){
                int acak = (int) (Math.random()*3+1);
                if (acak==1){
                    bot("perkataan anda tidak ada yang sesuai dengan kata kunci");
                }else if(acak==2){
                    bot("saya tidak mengerti maksud anda");
                }else if(acak==3){
                    bot("saya sarankan ketik 'help' terlebih dahulu");
                }
            }   
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        
    }//GEN-LAST:event_send_btnActionPerformed

    private void menu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu2ActionPerformed
        // TODO add your handling code here:
        new Menu().setVisible(true);
        dispose();
    }//GEN-LAST:event_menu2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Chat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Chat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Chat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Chat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Chat().setVisible(true);
            }
        });
    }
    public void bot(String s){
        TA.append("\nAI     : "+s);
    }
    public void pisah(String t){
        String[] kata = t.split(",");
        for (counter = 0; counter < kata.length; counter++){
            System.out.println(kata[counter]);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea TA;
    private javax.swing.JTextField TF;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenu menu2;
    private javax.swing.JMenuBar menubar;
    private javax.swing.JButton send_btn;
    // End of variables declaration//GEN-END:variables
}
