/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package chatbot;
/**
 *
 * @author seto
 */

public class UI extends javax.swing.JFrame {

    /**
     * Creates new form UI
     */
    public UI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TA = new javax.swing.JTextArea();
        TF = new javax.swing.JTextField();
        send_btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Chatbot Pupuk Kujang");

        TA.setEditable(false);
        TA.setColumns(20);
        TA.setRows(5);
        TA.setText("ketik 'help' untuk melihat daftar kata kunci\n\nAI     : Selamat Datang, Ada yang bisa saya bantu? ");
        jScrollPane1.setViewportView(TA);

        send_btn.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        send_btn.setText("Kirim");
        send_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                send_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 432, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(TF)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(send_btn)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 491, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(send_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TF))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void send_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_send_btnActionPerformed
        // TODO add your handling code here:
        String psn=TF.getText();    // memasukan input user ke variable pesan
        TA.append("\nYou : "+psn);  // menampilkan variable pesan ke textarea
        psn = psn.toLowerCase();    //mengkonvert huruf ke huruf kecil semua
        if(psn.contains("visi")||psn.contains("misi")){
            bot("\nVisi : Menjadi Industri Kimia dan Pendukung P ertanian yang Berdaya Saing dalam Skala Nasional\nMisi : Menghasilkan Produk Bermutu dan Melakukan Perdagangan yang Berdaya Saing Tinggi dengan Mengutamakan Kepuasan Pelanggan\nTata Nilai / Budaya : SIAP(Selamat,Integritas,Adaptif,Pelanggan)");
        }else if(psn.contains("sejarah")){
            bot("\nPT Pupuk Kujang didirikan pada tanggal 9 Juni 1975 dengan dana US$ 260 juta merupakan pinjaman dari Pemerintah Iran sebesar US$ 200 Juta, serta Penyertaan Modal Pemerintah (PMP) Indonesia sebesar US$ 60 juta.\n Pinjaman kepada Pemerintah Iran telah dilunasi tahun 1989. Pembangunan pabrik Pupuk Kujang pertama yang kemudian diberi nama Pabrik Kujang 1A dengan kapasitas produksi 570.000 ton/tahun urea dan 330.000 ton/tahun amoniak pembangunannya dilaksanakan oleh kontraktor utama Kellogg Overseas Corporation (USA) dan Toyo Engineering Corporation (Japan).\n Pembangunan Pabrik Kujang 1A ini berhasil dibangun selama 36 bulan dan diresmikan oleh Presiden Republik Indonesia pada tanggal 12 Desember 1978. PT Pupuk Kujang merupakan anak perusahaan dari BUMN Pupuk di Indonesia yaitu PT Pupuk Indonesia Holding Company.");
        }else if(psn.contains("anak")||psn.contains("afiliasi")){
            bot("\n1. PT SINTAS KURAMA PERDANA (Pabrik Asam Formiat)\n2. PT CLARIANT KUJANG CATALYSTS (Pabrik Katalis)\n3. PT PEROKSIDA INDONESIA PRATAMA (Pabrik Hidrogen Peroksida)\n4. PT MULTI NITROTAMA KIMIA (Pabrik Ammonium Nitrat)\n5. PT KAWASAN INDUSTRI KUJANG CIKAMPEK\n6. PT Pupuk Indonesia Energi ( PERUSAHAAN ENERGI )\n7. PT Pupuk Indonesia Pangan ( PERUSAHAAN AGRIBISNIS )");
        }else if(psn.contains("kontak")||psn.contains("alamat")){
            bot("\n(Kantor Pusat) Jl. Jend. A. Yani No. 39 Cikampek 41373 Kabupaten Karawang Jawa Barat\nTelp :  (0264) 316141, 317007  TOLL FREE : 0800-100-3001  (0264) 314235, 314335 | Klinik Tani : 0813 8333 1133\n(Kantor Jakarta) Jl. Letjen S. Parman No. Kav. 101 Grogol Petamburan, Tomang - Jakarta Barat 11440 | Wisma Pusri Lt. 4 ");
        }else if(psn.contains("2014")){
            bot("\nUrea : 910.560\nAmonia : 591.999\nNPK : 66.520\nOrganik : 34.759");
        }else if(psn.contains("2015")){
            bot("\nUrea : 950.272\nAmonia : 603.254\nNPK : 107.357\nOrganik : 44.889");
        }else if(psn.contains("2016")){
            bot("\nUrea : 953.313\nAmonia : 610.338\nNPK : 103.056\nOrganik : 25.631");
        }else if(psn.contains("2017")){
            bot("\nUrea : 1.004.139\nAmonia : 632.701\nNPK : 177.517\nOrganik : 46.327");
        }else if(psn.contains("2018")){
            bot("\nUrea : 896.721\nAmonia : 591.957\nNPK : 176.863\nOrganik : 59.544");
        }else if(psn.contains("data")){
            bot("anda ingin melihat data tahun berapa?");
        }else if(psn.contains("help")){
            bot("\nVisi dan Misi - menampilkan visi misi perusahaan\nSejarah - menampilkan sejarah perusahaan\nAnak Perusahaan - menampilkan daftar anak perusahaan\nKontak/Alamat - menampilkan nomor kontak dan alamat\nData produksi (tahun) - menampilkan data produksi sesuai tahun\nWeb - menampilkan alamat web perusahaan\n\nNote : kecil besar huruf tidak mempengaruhi program");
        }else if(psn.contains("web")){
            bot("www.pupuk-kujang.co.id");
        }else{
            int acak = (int) (Math.random()*3+1);
            if (acak==1){
                bot("perkataan anda tidak ada yang sesuai dengan kata kunci");
            }else if(acak==2){
                bot("saya tidak mengerti maksud anda");
            }else if(acak==3){
                bot("saya sarankan ketik 'help' terlebih dahulu");
            }
        }
        TF.setText("");
    }//GEN-LAST:event_send_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UI().setVisible(true);
            }
        });
    }
    
    public void bot(String s){
        TA.append("\nAI     : "+s);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea TA;
    private static javax.swing.JTextField TF;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton send_btn;
    // End of variables declaration//GEN-END:variables
}
